apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ph.users.full_name" . }}
spec:
  replicas: {{ .Values.users.replicas }}
  selector:
    matchLabels:
      app: {{ template "ph.users.full_name" . }}
  template:
    metadata:
      labels:
        app: {{ template "ph.users.full_name" . }}
    spec:
      containers:
      - name: operator
        image: {{ default (printf "benwright/auth-service/users:%s" .Chart.AppVersion) .Values.users.image }}
        envFrom:
        - secretRef:
            name: "{{ .Values.users.postgres.secret }}"
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace }}