apiVersion: ponglehub.co.uk/v1alpha1
kind: CockroachClient
metadata:
  name: {{ template "ph.users.full_name" . }}
spec:
  deployment: {{ .Values.cockroach.deployment }}
  database: {{ .Values.userService.cockroach.database }}
  username: {{ .Values.userService.cockroach.username }}
  secret: {{ .Values.userService.cockroach.secret }}