apiVersion: ponglehub.co.uk/v1alpha1
kind: CockroachClient
metadata:
  name: {{ template "ph.users.full_name" . }}
spec:
  dbRef:
    name: {{ .Values.cockroach.deployment }}
    namespace: {{ .Release.Namespace }}
  database: {{ .Values.users.cockroach.database }}
  username: {{ .Values.users.cockroach.username }}
  secret: {{ .Values.users.cockroach.secret }}