apiVersion: ponglehub.co.uk/v1alpha1
kind: PostgresClient
metadata:
  name: {{ template "ph.migrations.full_name" . }}
spec:
  cluster:
    name: {{ .Values.postgres.deployment }}
    namespace: {{ .Release.Namespace }}
  database: {{ .Values.users.postgres.database }}
  username: {{ .Values.users.migrations.username }}
  secret: {{ .Values.users.migrations.secret }}
  permission: admin