{{- range $path, $data := .Files.Glob "resources/*.sql" }}
{{- $name := trimSuffix ".sql" (base $path) }}
{{- $id := last (regexSplit "-" $name -1) }}
apiVersion: ponglehub.co.uk/v1alpha1
kind: CockroachMigration
metadata:
  name: {{ $name }}
spec:
  dbRef:
    name: {{ $.Values.cockroach.deployment }}
    namespace: {{ $.Release.Namespace }}
  database: {{ $.Values.users.cockroach.database }}
  index: {{ $id }}
  migration: |-
    {{- toString $data | nindent 4 }}
{{- end }}