{{- $cert := genSelfSignedCert .Values.domain nil nil 365 -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "ph.tokens.full_name" . }}-keyfile
type: Opaque
data:
    keyfile: {{ .Values.tokenKeyfile | b64enc }}
    signingCert: {{ $cert.Cert | b64enc }}
    signingKey: {{ $cert.Key | b64enc }}
