{{- $cert := genSelfSignedCert .Values.domain nil nil 365 -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "ph.tokens.full_name" . }}-signing-cert
type: Opaque
data:
    signing.crt: {{ $cert.Cert | b64enc }}
    signing.key: {{ $cert.Key | b64enc }}
