{{- if .Values.cockroach.create }}
apiVersion: ponglehub.co.uk/v1alpha1
kind: PostgresCluster
metadata:
    name: {{ .Values.postgres.deployment }}
    namespace: {{ .Release.Namespace }}
spec:
    storage: {{ .Values.postgres.storage }}
{{- end }}