apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-validator
spec:
  forwardAuth:
    address: http://{{ template "ph.verify.full_name" . }}.{{ .Release.Namespace }}.svc.cluster.local
    authResponseHeaders:
    - x-auth-user