name: Tag Publish
run-name: ${{ github.actor }} is publishing a new tag version
on:
  push:
    tags:
      - '*'
jobs:
  go-images:
    strategy:
      matrix:
        app: [forms, tokens, users, verify, init]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Install Just
        uses: extractions/setup-just@v2
      - name: Build
        run: just build cmd/${{ matrix.app }} benwright/auth-server/${{ matrix.app }}:${{ github.ref_name }}
      - name: Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: benwright/auth-server/${{ matrix.app }}:${{ github.ref_name }}
